const UPDATE_GALLERY = 'UPDATE_GALLERY'
const ERROR = 'ERROR'
const SET_SECTION = 'SET_SECTION'
const SET_SORT = 'SET_SORT'
const SET_WINDOW = 'SET_WINDOW'
const SET_SHOW_VIRAL = 'SET_SHOW_VIRAL'
const START_LOADING = 'START_LOADING'
const FINISH_LOADING = 'FINISH_LOADING'
const UPDATE_IMAGE = 'UPDATE_IMAGE'

export {
    UPDATE_GALLERY,
    ERROR,
    SET_SECTION,
    SET_SORT,
    SET_WINDOW,
    SET_SHOW_VIRAL,
    START_LOADING,
    FINISH_LOADING,
    UPDATE_IMAGE
}